#include "extendedVanillaItemTable.h"
#include "ItemTableManager.h"
#include "z64.h"
#include "macros.h"
#include "soh/Enhancements/custom-message/CustomMessageTypes.h"

extern "C" void ExtendedVanillaItemTable_Init(void) {
    static GetItemEntry extendedVanillaGetItemTable[] = {
        // clang-format off
        GET_ITEM(ITEM_SONG_LULLABY,     OBJECT_GI_MELODY,       GID_SONG_ZELDA,       0xD4,                        0x80, CHEST_ANIM_LONG, ITEM_CATEGORY_MAJOR, MOD_EXTENDED_VANILLA, EXT_ZELDAS_LULLABY),
        GET_ITEM(ITEM_SONG_EPONA,       OBJECT_GI_MELODY,       GID_SONG_EPONA,       0xD2,                        0x80, CHEST_ANIM_LONG, ITEM_CATEGORY_MAJOR, MOD_EXTENDED_VANILLA, EXT_EPONAS_SONG),
        GET_ITEM(ITEM_SONG_SARIA,       OBJECT_GI_MELODY,       GID_SONG_SARIA,       0xD1,                        0x80, CHEST_ANIM_LONG, ITEM_CATEGORY_MAJOR, MOD_EXTENDED_VANILLA, EXT_SARIAS_SONG),
        GET_ITEM(ITEM_SONG_SUN,         OBJECT_GI_MELODY,       GID_SONG_SUN,         0xD3,                        0x80, CHEST_ANIM_LONG, ITEM_CATEGORY_MAJOR, MOD_EXTENDED_VANILLA, EXT_SUNS_SONG),
        GET_ITEM(ITEM_SONG_TIME,        OBJECT_GI_MELODY,       GID_SONG_TIME,        0xD5,                        0x80, CHEST_ANIM_LONG, ITEM_CATEGORY_MAJOR, MOD_EXTENDED_VANILLA, EXT_SONG_OF_TIME),
        GET_ITEM(ITEM_SONG_STORMS,      OBJECT_GI_MELODY,       GID_SONG_STORM,       0xD6,                        0x80, CHEST_ANIM_LONG, ITEM_CATEGORY_MAJOR, MOD_EXTENDED_VANILLA, EXT_SONG_OF_STORMS),
        GET_ITEM(ITEM_SONG_MINUET,      OBJECT_GI_MELODY,       GID_SONG_MINUET,      0x73,                        0x80, CHEST_ANIM_LONG, ITEM_CATEGORY_MAJOR, MOD_EXTENDED_VANILLA, EXT_MINUET_OF_FOREST),
        GET_ITEM(ITEM_SONG_BOLERO,      OBJECT_GI_MELODY,       GID_SONG_BOLERO,      0x74,                        0x80, CHEST_ANIM_LONG, ITEM_CATEGORY_MAJOR, MOD_EXTENDED_VANILLA, EXT_BOLERO_OF_FIRE),
        GET_ITEM(ITEM_SONG_SERENADE,    OBJECT_GI_MELODY,       GID_SONG_SERENADE,    0x75,                        0x80, CHEST_ANIM_LONG, ITEM_CATEGORY_MAJOR, MOD_EXTENDED_VANILLA, EXT_SERENADE_OF_WATER),
        GET_ITEM(ITEM_SONG_REQUIEM,     OBJECT_GI_MELODY,       GID_SONG_REQUIEM,     0x76,                        0x80, CHEST_ANIM_LONG, ITEM_CATEGORY_MAJOR, MOD_EXTENDED_VANILLA, EXT_REQUIEM_OF_SPIRIT),
        GET_ITEM(ITEM_SONG_NOCTURNE,    OBJECT_GI_MELODY,       GID_SONG_NOCTURNE,    0x77,                        0x80, CHEST_ANIM_LONG, ITEM_CATEGORY_MAJOR, MOD_EXTENDED_VANILLA, EXT_NOCTURNE_OF_SHADOW),
        GET_ITEM(ITEM_SONG_PRELUDE,     OBJECT_GI_MELODY,       GID_SONG_PRELUDE,     0x78,                        0x80, CHEST_ANIM_LONG, ITEM_CATEGORY_MAJOR, MOD_EXTENDED_VANILLA, EXT_PRELUDE_OF_LIGHT),
        GET_ITEM(ITEM_MEDALLION_FOREST, OBJECT_GI_MEDAL,        GID_MEDALLION_FOREST, 0x3E,                        0x80, CHEST_ANIM_LONG, ITEM_CATEGORY_MAJOR, MOD_EXTENDED_VANILLA, EXT_FOREST_MEDALLION),
        GET_ITEM(ITEM_MEDALLION_FIRE,   OBJECT_GI_MEDAL,        GID_MEDALLION_FIRE,   0x3C,                        0x80, CHEST_ANIM_LONG, ITEM_CATEGORY_MAJOR, MOD_EXTENDED_VANILLA, EXT_FIRE_MEDALLION),
        GET_ITEM(ITEM_MEDALLION_WATER,  OBJECT_GI_MEDAL,        GID_MEDALLION_WATER,  0x3D,                        0x80, CHEST_ANIM_LONG, ITEM_CATEGORY_MAJOR, MOD_EXTENDED_VANILLA, EXT_WATER_MEDALLION),
        GET_ITEM(ITEM_MEDALLION_SPIRIT, OBJECT_GI_MEDAL,        GID_MEDALLION_SPIRIT, 0x3F,                        0x80, CHEST_ANIM_LONG, ITEM_CATEGORY_MAJOR, MOD_EXTENDED_VANILLA, EXT_SPIRIT_MEDALLION),
        GET_ITEM(ITEM_MEDALLION_SHADOW, OBJECT_GI_MEDAL,        GID_MEDALLION_SHADOW, 0x41,                        0x80, CHEST_ANIM_LONG, ITEM_CATEGORY_MAJOR, MOD_EXTENDED_VANILLA, EXT_SHADOW_MEDALLION),
        GET_ITEM(ITEM_MEDALLION_LIGHT,  OBJECT_GI_MEDAL,        GID_MEDALLION_LIGHT,  0x40,                        0x80, CHEST_ANIM_LONG, ITEM_CATEGORY_MAJOR, MOD_EXTENDED_VANILLA, EXT_LIGHT_MEDALLION),
        GET_ITEM(ITEM_KOKIRI_EMERALD,   OBJECT_GI_JEWEL,        GID_KOKIRI_EMERALD,   0x80,                        0x80, CHEST_ANIM_LONG, ITEM_CATEGORY_MAJOR, MOD_EXTENDED_VANILLA, EXT_KOKIRI_EMERALD),
        GET_ITEM(ITEM_GORON_RUBY,       OBJECT_GI_JEWEL,        GID_GORON_RUBY,       0x81,                        0x80, CHEST_ANIM_LONG, ITEM_CATEGORY_MAJOR, MOD_EXTENDED_VANILLA, EXT_GORON_RUBY),
        GET_ITEM(ITEM_ZORA_SAPPHIRE,    OBJECT_GI_JEWEL,        GID_ZORA_SAPPHIRE,    0x82,                        0x80, CHEST_ANIM_LONG, ITEM_CATEGORY_MAJOR, MOD_EXTENDED_VANILLA, EXT_ZORA_SAPPHIRE),
        GET_ITEM(ITEM_SWORD_MASTER,     OBJECT_TOKI_OBJECTS,    GID_SWORD_BGS,        TEXT_CUSTOM_ITEM, 0x80, CHEST_ANIM_LONG, ITEM_CATEGORY_MAJOR, MOD_EXTENDED_VANILLA, EXT_MASTER_SWORD),
        // clang-format on
    };
    ItemTableManager::Instance->AddItemTable(MOD_EXTENDED_VANILLA);
    for (uint8_t i = 0; i < ARRAY_COUNT(extendedVanillaGetItemTable); i++) {
        ItemTableManager::Instance->AddItemEntry(MOD_EXTENDED_VANILLA, extendedVanillaGetItemTable[i].getItemId,
                                                 extendedVanillaGetItemTable[i]);
    }
}
