#ifndef SHIP_INF_H
#define SHIP_INF_H

#define SAVEFILE_ENTRANCES_DISCOVERED_IDX_COUNT 66
#define SAVEFILE_SCENES_DISCOVERED_IDX_COUNT 4

typedef enum ShipFlag {
    SHIP_FLAG_BOSS_RUSH_SPIRIT_TEMPLE_COMPLETE,
    SHIP_FLAG_BOSS_RUSH_SHADOW_TEMPLE_COMPLETE,
    SHIP_FLAG_MAX,
} ShipFlag;

#endif
